# @file config/config.yaml
# @description Configuration for the Cablegate PDF Dataset Project
# @version 1.0.7
# @license MIT

dataset:
  name: "cablegate-pdf-dataset"
  type: "parquet"
paths:
  root: "."
  assets: "./assets"
  data: "./data"
  raw: "./data/raw"
  process: "./data/process"
  database: "./data/db"
  export: "./data/export"
  generate: "./data/generate"
  processed_data: "processed_data"
  processed_data_train: "{{paths.processed_data}}/train"
  templates: "{{paths.assets}}/templates"
database:
  env: "development"
  name: "thinking-dataset"
  type: "sqlite"
  url: "{{database.type}}:///data/db/{{database.name}}.db"
  config:
    pool_size: 5
    max_overflow: 10
    connect_timeout: 30
    read_timeout: 30
    log_queries: True
files:
  include:
  - "train-00000-of-00001.{{dataset.type}}"
  exclude:
  - "cleaned_data.{{dataset.type}}"
  load:
  - "{{paths.process}}/{file_name}"
pipelines:
- pipeline:
    name: "process"
    description: "Default prepare pipeline"
    config:
      prepare_file: "{file_base}{file_ext}"
    pipes:
    - pipe:
        type: "SubsetPipe"
        config:
          rows: [ "all" ]
          columns: [ "all" ]
    - pipe:
        type: "AddIdPipe"
        config: {}
    - pipe:
        type: "DropColumnsPipe"
        config:
          columns: [ "file_name" ]
    - pipe:
        type: "RemapColumnsPipe"
        config:
          column_mapping:
            pdf_content: cable
          column_order:
          - id
          - cable
    - pipe:
        type: "RemoveDuplicatesPipe"
        config:
          columns: [ "auto" ]
    - pipe:
        type: "HandleMissingValuesPipe"
        config:
          columns: [ "auto" ]
          remove_partials: True
          allow_empty: False
    - pipe:
        type: "NormalizeTextPipe"
        config:
          columns: [ "cable" ]
          contractions:
            "ain't": "am not"
            "aren't": "are not"
            "can't": "cannot"
            "couldn't": "could not"
            "didn't": "did not"
            "doesn't": "does not"
            "don't": "do not"
            "hadn't": "had not"
            "hasn't": "has not"
            "haven't": "have not"
            "he'd": "he would"
            "he'll": "he will"
            "he's": "he is"
            "I'd": "I would"
            "I'll": "I will"
            "I'm": "I am"
            "I've": "I have"
            "isn't": "is not"
            "it'd": "it would"
            "it'll": "it will"
            "it's": "it is"
            "let's": "let us"
            "mightn't": "might not"
            "mustn't": "must not"
            "shan't": "shall not"
            "she'd": "she would"
            "she'll": "she will"
            "she's": "she is"
            "shouldn't": "should not"
            "that'd": "that would"
            "that's": "that is"
            "there'd": "there would"
            "there's": "there is"
            "they'd": "they would"
            "they'll": "they will"
            "they're": "they are"
            "they've": "they have"
            "we'd": "we would"
            "we're": "we are"
            "we've": "we have"
            "weren't": "were not"
            "what'll": "what will"
            "what're": "what are"
            "what's": "what is"
            "what've": "what have"
            "where's": "where is"
            "who'd": "who would"
            "who'll": "who will"
            "who's": "who is"
            "who've": "who have"
            "won't": "will not"
            "wouldn't": "would not"
            "you'd": "you would"
            "you'll": "you will"
            "you're": "you are"
            "you've": "you have"
          terms:
            "i.e": "that is "
            "afg": "afghanistan"
            "alg": "algeria"
            "amb": "ambassador"
            "apec": "asia-pacific economic cooperation"
            "arg": "argentina"
            "asean": "association of southeast asian nations"
            "aus": "australia"
            "aut": "austria"
            "aze": "azerbaijan"
            "bgr": "bulgaria"
            "bih": "bosnia and herzegovina"
            "blr": "belarus"
            "blz": "belize"
            "bra": "brazil"
            "brb": "barbados"
            "brn": "brunei"
            "btn": "bhutan"
            "bwa": "botswana"
            "can": "canada"
            "cia": "central intelligence agency"
            "chn": "china"
            "col": "colombia"
            "cplp": "community of portuguese language countries"
            "cri": "costa rica"
            "cub": "cuba"
            "cyp": "cyprus"
            "cze": "czech republic"
            "deu": "germany"
            "dept": "department"
            "dhs": "department of homeland security"
            "dod": "department of defense"
            "doc": "document"
            "drc": "democratic republic of congo"
            "dpi": "department of public information"
            "ecu": "ecuador"
            "egy": "egypt"
            "est": "estonia"
            "eu": "european union"
            "ext": "external"
            "fbi": "federal bureau of investigation"
            "fin": "finland"
            "fm": "foreign minister"
            "fr": "france"
            "fy": "fiscal year"
            "g7": "group of seven"
            "g8": "group of eight"
            "g20": "group of twenty"
            "gb": "gigabytes"
            "gdp": "gross domestic product"
            "gen": "general"
            "gov": "government"
            "guy": "guyana"
            "hun": "hungary"
            "imf": "international monetary fund"
            "ind": "india"
            "int": "intelligence"
            "int'l": "international"
            "irn": "iran"
            "irq": "iraq"
            "isr": "israel"
            "ita": "italy"
            "jpn": "japan"
            "kb": "kilobytes"
            "kgz": "kyrgyzstan"
            "kmr": "comoros"
            "kor": "south korea"
            "kwt": "kuwait"
            "lao": "laos"
            "lbn": "lebanon"
            "lby": "libya"
            "lka": "sri lanka"
            "ltu": "lithuania"
            "lux": "luxembourg"
            "mb": "megabytes"
            "mex": "mexico"
            "mil": "military"
            "min": "minister"
            "mne": "montenegro"
            "moz": "mozambique"
            "mrt": "mauritania"
            "mus": "mauritius"
            "mys": "malaysia"
            "nam": "namibia"
            "nato": "north atlantic treaty organization"
            "npl": "nepal"
            "nsa": "national security agency"
            "nzl": "new zealand"
            "opec": "organization of the petroleum exporting countries"
            "pak": "pakistan"
            "pan": "panama"
            "per": "peru"
            "phl": "philippines"
            "pol": "poland"
            "prt": "portugal"
            "qat": "qatar"
            "red cross": "international red cross"
            "rep": "representative"
            "rpt": "report"
            "rus": "russia"
            "sau": "saudi arabia"
            "sdn": "sudan"
            "sec": "secretary"
            "sgp": "singapore"
            "slv": "el salvador"
            "som": "somalia"
            "sur": "suriname"
            "swe": "sweden"
            "syr": "syria"
            "tgo": "togo"
            "tha": "thailand"
            "tls": "timor-leste"
            "tto": "trinidad and tobago"
            "tun": "tunisia"
            "tur": "turkey"
            "uae": "united arab emirates"
            "uk": "united kingdom"
            "un": "united nations"
            "unicef": "united nations children's fund"
            "u.n.": "united nations"
            "u.s.": "united states"
            "usa": "united states of america"
            "usaid": "united states agency for international development"
            "usmc": "united states marine corps"
            "uzb": "uzbekistan"
            "vat": "vatican city"
            "vct": "saint vincent and the grenadines"
            "ven": "venezuela"
            "vnm": "vietnam"
            "who": "world health organization"
            "world bank": "world bank"
            "wto": "world trade organization"
            "yem": "yemen"
            "zaf": "south africa"
            "zmb": "zambia"
            "zwe": "zimbabwe"
            "acp": "african, caribbean and pacific group of states"
            "afdb": "african development bank"
            "bof": "board of finance"
            "comesa": "common market for eastern and southern africa"
            "cpp": "communist party of poland"
            "dfid": "department for international development"
            "eap": "east asia and pacific"
            "eas": "east african states"
            "ec": "european commission"
            "eca": "economic commission for africa"
            "ecs": "economic and social council"
            "ecowas": "economic community of west african states"
            "eur": "europe"
            "fas": "foreign agricultural service"
            "gop": "government of pakistan"
            "gpe": "global partnership for education"
            "iaci": "inter-american commission on human rights"
            "iaea": "international atomic energy agency"
            "iba": "international bar association"
            "icc": "international criminal court"
            "icj": "international court of justice"
            "icrc": "international committee of the red cross"
            "ida": "international development association"
            "idb": "inter-american development bank"
            "ifc": "international finance corporation"
            "ilo": "international labour organization"
            "imo": "international maritime organization"
            "ioc": "international olympic committee"
            "ipa": "international peace academy"
            "ipcc": "intergovernmental panel on climate change"
            "ipu": "international parliamentary union"
            "isa": "international sugar agreement"
            "itc": "international trade centre"
            "itar": "international traffic in arms regulations"
            "itu": "international telecommunication union"
            "jica": "japan international cooperation agency"
            "kpc": "kosovo police service"
            "ldc": "least developed countries"
            "mcc": "millennium challenge corporation"
            "mfap": "ministry of foreign affairs and trade"
            "nafta": "north american free trade agreement"
            "ndp": "national development plan"
            "npc": "national people's congress"
            "oecd": "organization for economic co-operation and development"
            "osce": "organization for security and co-operation in europe"
            "pbc": "peacebuilding commission"
            "ppa": "personal protection act"
            "prc": "people's republic of china"
            "prodem": "program of democratic empowerment"
            "roa": "republic of armenia"
            "rsa": "republic of south africa"
            "saaf": "south african air force"
            "saarc": "south asian association for regional cooperation"
            "sadcc": "southern african development coordination conference"
            "sadf": "south african defense force"
            "sadc": "southern african development community"
            "sap": "structural adjustment program"
            "sars": "severe acute respiratory syndrome"
            "sc": "security council"
            "sdgs": "sustainable development goals"
            "snds": "strategic national development strategy"
            "spr": "strategic petroleum reserve"
            "ssa": "sub-saharan africa"
            "tpp": "trans-pacific partnership"
            "uar": "united arab republic"
            "unhrc": "united nations human rights council"
            "unstats": "united nations statistical commission"
            "uxo": "unexploded ordnance"
            "vac": "voluntary advisory committee"
            "wipo": "world intellectual property organization"
            "wmd": "weapons of mass destruction"
    - pipe:
        type: "FilterBySizePipe"
        config:
          column_name: "cable"
          min_size: 500
          max_size: 0
    - pipe:
        type: "ChunkingPipe"
        config:
          columns: [ "cable" ]
          min_chunk_size: 500
          max_chunk_size: 10000
- pipeline:
    name: "export"
    description: "Default export pipeline"
    config: {}
    pipes:
    - pipe:
        type: "ExportTablesPipe"
        config:
          tables: [ "all" ]
          columns: [ "auto" ]
          shard_size: 1000000
          pattern: "{{dataset.name}}-{split_name}-{split_info}.{{dataset.type}}"
          path: "{{paths.export}}/{{paths.processed_data_train}}"
          schema: [ "id", "cable" ]
          drop_columns: True
          fill_value: "null"
- pipeline:
    name: "upload"
    description: "Default upload pipeline"
    config: {}
    pipes:
    - pipe:
        type: "FileExtractorPipe"
        config:
          path: "{{paths.export}}/{{paths.processed_data_train}}"
          filter: "{{dataset.type}}"
    - pipe:
        type: "FileUploadHfApiPipe"
        config:
          org: "${HF_ORG}"
          user: "${HF_USER}"
          token: "${HF_WRITE_TOKEN}"
          dataset: "{{dataset.name}}"
          repo_type: "dataset"
          remote_path: "{{paths.processed_data_train}}"
          dry_run: False
- pipeline:
    name: "generate"
    description: "Generate synthetic data pipeline"
    config: {}
    pipes:
    - pipe:
        type: "LoadTemplatesPipe"
        config:
          flush: True
          template: "{{paths.templates}}/generate_cable.json"
    - pipe:
        type: "SeedTemplatesPipe"
        config:
          tables:
          - table: "train-00000-of-00001"
            columns: [ "cable" ]
          seed_length: 10000
          seed_offset: 0
          limit: 3
          batch_size: 1000000
          shard_size: 4096
          offset: 0
          save: True
          save_path: "{{paths.generate}}"
          save_file: "seed-templates-pipe-{batch_info}.{{dataset.type}}"
