dataset:
  hfapi:
    name: "cablegate-pdf-dataset"
    type: "parquet"
  database:
    url: "sqlite:///data/db/{name}.db"
  paths:
    root: "."
    database: "db"
    data: "data"
    raw: "raw"
    processed: "processed"
  files:
    include:
    - "train-00000-of-00001.parquet"
    exclude:
    - "cleaned_data.parquet"
    load:
    - "{file_root}_prepare{file_ext}"
  pipelines:
  - pipeline:
      name: "prepare"
      description: "Default prepare pipeline"
      config:
        prepare_file: "{file_base}_prepare{file_ext}"
      pipes:
      - pipe:
          name: "Remove Duplicates"
          type: "RemoveDuplicatesPipe"
          config:
            columns: [ "auto" ]
      - pipe:
          name: "Handle Missing Values"
          type: "HandleMissingValuesPipe"
          config:
            columns: [ "auto" ]
            remove_partials: True
            allow_empty: False
      - pipe:
          name: "Clean Whitespace"
          type: "CleanWhitespacePipe"
          config:
            columns: [ "pdf_content" ]
