dataset:
  huggingface:
    name: "cablegate-pdf-dataset"
    type: "parquet"
  database:
    url: "sqlite:///data/db/{name}.db"
  paths:
    root: "."
    data: "data"
    database: "db"
  files:
    include:
    - "train-00000-of-00001.parquet"
    exclude:
    - "cleaned_data.parquet"
