dataset:
  hfapi:
    name: "cablegate-pdf-dataset"
    type: "parquet"
  database:
    url: "sqlite:///data/db/{name}.db"
  paths:
    root: "."
    database: "db"
    data: "data"
    raw: "raw"
    processed: "processed"
  files:
    include:
    - "train-00000-of-00001.parquet"
    exclude:
    - "cleaned_data.parquet"
  pipelines:
  - pipeline:
      name: "preprocessor"
      description: "Default preprocessing pipeline"
      pipes:
      - pipe:
          name: "Remove Duplicates"
          type: "RemoveDuplicatesPipe"
          config:
            columns: [ "pdf_content", "filename" ]
      - pipe:
          name: "Handle Missing Values"
          type: "HandleMissingValuesPipe"
          config:
            columns: [ "pdf_content", "filename" ]
